name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and I look forward to work with you to resolve the issue. Keep up the great work!'
          pr-message: 'Great job, @${{ github.actor }}! 🎉 Thank you for submitting your first pull request. Your contribution is valuable and I appreciate your efforts to improve my project.'
          footer: 'I will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check my [contributing guidelines](https://github.com/dakshsinghrathore/ISRO-web/blob/main/CONTRIBUTING.md)'
